### ISSUE TITLE
Score definition 

### ISSUE THREAD

**Issue by jsbean** [dn-m/Metronome#4]
Use `YAML` using a schema such as:

```YAML
- 4/4 # measure
  tempo: 60 # non-interpolating tempo on downbeat
- 5/16
- 9/32
  - 5/32: # offset in measure
    tempo: 72 # sub. tempo
- 4/4:
  tempo_interp: 240 # begin interpolating tempo on downbeat
- 4/4
- 4/4
- 4/4
- 4/4
- 4/4
- 4/4
- 4/4
- 4/4:
  - 2: # on beat 3
    tempo: 30 # end of tempo interpolation (240 -> 30)
```
